### ISSUE TITLE
wepy build 后缺少一层dist，报错

### ISSUE THREAD

**Issue by billyshen26** [heeroluo/wepy-html#5]
![image](https://user-images.githubusercontent.com/5089845/51240241-48f0e580-19b6-11e9-8159-7020ab238f9b.png)
如图，我的npm为 6.3.0， node为8.11.2，跑wepy build后，npm文件夹里面的wepy-html底下缺少一层dist，导致引用有问题，请问是什么原因

**Comment by heeroluo** [comment]
应该是 build 的时候少了一层文件夹。如果急用可以把项目 dist 目录下的文件拷到项目里面用。
