### ISSUE TITLE
使用两个组件的时候，不显示任何内容

### ISSUE THREAD

**Issue by lvsjack** [heeroluo/wepy-html#8]
![Xnip2019-05-30_19-36-47](https://user-images.githubusercontent.com/17427372/58630556-5ded6600-8312-11e9-8f09-d5ede7f39055.jpg)

### 通过开发者工具看到有数据了，这些数据如果在单个组件的时候都显示正常，但是多个组件就显示不出来。请帮忙查看。
![image](https://user-images.githubusercontent.com/17427372/58630003-a3a92f00-8310-11e9-9d4e-63b5039bfaab.png)

**Comment by heeroluo** [comment]
您好，本组件暂不支持在一个页面中多次嵌入。
该功能会列入后续版本的规划中。

**Comment by lvsjack** [comment]
好的，期待，还是给了我很多帮助。
